[build]
  functions = "netlify-functions"
  publish = "public"
  command = "go build -o netlify-functions/app"

[context.production.environment]
  PORT = "8080"  # This is important to make sure the backend runs on the specified port

[[redirects]]
  from = "/api/*"
  to = "/netlify-functions/api/$1"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Expose-Headers = "Set-Cookie"
